---
- name: Create kustomize patch
  ansible.builtin.copy:
    src: p_postgresql.yaml
    dest: "{{ kustomize_directory }}/patch.yaml"
    owner: magma
    group: magma
    mode: '0644'

- name: Install PostgreSQL
  kubernetes.core.helm:
    name: postgresql
    chart_ref: bitnami/postgresql
    release_namespace: "{{ magma_namespace }}"
    chart_version: "{{ postgresql_chart_version }}"
    create_namespace: true
    post_renderer: "{{ kustomize_install_path }}/kust.sh"
    values:
      global:
        postgresql:
          auth:
            postgresPassword: "{{ postgresql_password }}"
            database: "{{ postgresql_database }}"
