---
- name: Create kustomize patch
  ansible.builtin.copy:
    src: p_openebs.yaml
    dest: "{{ kustomize_directory }}/patch.yaml"
    owner: magma
    group: magma
    mode: '0644'

- name: Install OpenEBS
  kubernetes.core.helm:
    name: openebs
    chart_ref: openebs/openebs
    release_namespace: openebs
    chart_version: "{{ openebs_chart_version }}"
    create_namespace: true
    post_renderer: "{{ kustomize_install_path }}/kust.sh"
    values:
      localprovisioner:
        hostpathClass:
          isDefaultClass: true
