apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-master
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: 301987362515.dkr.ecr.eu-central-1.amazonaws.com/external/elasticsearch/elasticsearch:7.17.3
        name: elasticsearch
