apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy
  namespace: orc8r
spec:
  template:
    spec:
      containers:
      - image: 301987362515.dkr.ecr.eu-central-1.amazonaws.com/external/haproxytech/haproxy-alpine:2.6.9
        name: haproxy
