apiVersion: apps/v1
kind: Deployment
metadata:
  name: orc8r-cwf
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: 301987362515.dkr.ecr.eu-central-1.amazonaws.com/external/magmacore/controller:1.8.0
        name: cwf
