---
- name: Create kustomize patch
  ansible.builtin.copy:
    src: p_elasticsearch.yaml
    dest: "{{ kustomize_directory }}/patch.yaml"
    owner: magma
    group: magma
    mode: '0644'

- name: Install Elasticsearch
  kubernetes.core.helm:
    name: elasticsearch
    chart_ref: elastic/elasticsearch
    release_namespace: "{{ magma_namespace }}"
    chart_version: "{{ elasticsearch_chart_version }}"
    create_namespace: true
    post_renderer: "{{ kustomize_install_path }}/kust.sh"
    values:
      replicas: 1
      extraEnvs:
        - name: discovery.type
          value: single-node
        - name: cluster.initial_master_nodes
          value: null
